build.gradle, src/main/java/curevengers/petit_cure/Dao/UserMapper.java, src/main/java/curevengers/petit_cure/Dto/testDto.java, src/main/java/curevengers/petit_cure/Service/testService.java, src/main/java/curevengers/petit_cure/Service/testServiceImpl.java, src/main/java/curevengers/petit_cure/controller/testhome.java, src/main/java/curevengers/petit_cure/project/test.java, src/main/resources/application.properties, src/main/resources/mappers/mapper.xml, src/main/resources/templates/test.html
=> feat:mybatis연동

src/main/java/curevengers/petit_cure/controller/testhome.java, src/main/resources/templates/main.html, src/main/resources/templates/test.html
=> feat:main view

src/main/java/curevengers/petit_cure/Dao/UserMapper.java, src/main/java/curevengers/petit_cure/Dto/freeBoardDTO.java, src/main/java/curevengers/petit_cure/Service/testService.java, src/main/java/curevengers/petit_cure/Service/testServiceImpl.java, src/main/java/curevengers/petit_cure/controller/testhome.java, src/main/resources/application.properties, src/main/resources/mappers/mapper.xml, src/main/resources/static/css/freeBoard.css, src/main/resources/static/css/main.css, src/main/resources/templates/freeBoard.html, src/main/resources/templates/main.html, src/main/resources/templates/view.html, src/main/resources/templates/write.html
=> feat : 자유게시판 DB 연동, 메인화면 include 구현, 게시판 글 자세히 보기

src/main/java/curevengers/petit_cure/controller/testhome.java, src/main/resources/application.properties, src/main/resources/static/css/freeBoard.css, src/main/resources/static/css/login.css, src/main/resources/static/css/main.css, src/main/resources/templates/freeBoard.html, src/main/resources/templates/login.html, src/main/resources/templates/main.html
=> feat:main view, login view

src/main/resources/static/css/main.css, src/main/resources/templates/Q&A.html, src/main/resources/templates/view.html, src/main/resources/templates/write.html
=> fix : 버그수정

src/main/resources/static/css/depBoard.css, src/main/resources/static/css/dpcheck.css, src/main/resources/templates/depBoard.html, src/main/resources/templates/dpcheck.html
=> feat: 우울증 게시판, 우울증 설문지 만들었습니다.

src/main/java/curevengers/petit_cure/controller/testhome.java, src/main/resources/static/css/main.css, src/main/resources/templates/Q&A.html, src/main/resources/templates/depBoard.html, src/main/resources/templates/healthcheck.html, src/main/resources/templates/healthcheckresult.html, src/main/resources/templates/main.html, src/main/resources/templates/mplus.html
=> refactor:진석님꺼랑 합치기

.gitignore, src/main/java/curevengers/petit_cure/controller/testhome.java, src/main/resources/static/css/main.css, src/main/resources/static/css/mplus.css, src/main/resources/static/css/write.css, src/main/resources/templates/depBoard.html, src/main/resources/templates/dpcheck.html, src/main/resources/templates/login.html, src/main/resources/templates/main.html, src/main/resources/templates/mplus.html, src/main/resources/templates/write.html
=> feat: 회원가입 view

src/main/java/curevengers/petit_cure/Dao/UserMapper.java, src/main/java/curevengers/petit_cure/Dto/QABoardDTO.java, src/main/java/curevengers/petit_cure/Service/testService.java, src/main/java/curevengers/petit_cure/Service/testServiceImpl.java, src/main/java/curevengers/petit_cure/controller/testhome.java, src/main/resources/application.properties, src/main/resources/mappers/mapper.xml, src/main/resources/static/css/write.css, src/main/resources/templates/Q&A.html, src/main/resources/templates/qaview.html, src/main/resources/templates/qawrite.html, src/main/resources/templates/write.html
=> feat : 자유, Q&A게시판 글쓰기 DB연동

src/main/resources/static/css/member.css, src/main/resources/static/css/memberdelete.css, src/main/resources/static/css/memberupdate.css, src/main/resources/templates/dpcheck.html, src/main/resources/templates/member.html, src/main/resources/templates/memberdelete.html, src/main/resources/templates/memberupdate.html
=> feat:  회원정보수정, 개인정보수정확인창,회원탈퇴창 만들어서

.gitignore, src/main/java/curevengers/petit_cure/common/email/Email.java, src/main/resources/templates/mplus.html
=> fix: gitignore수정

src/main/java/curevengers/petit_cure/security/SecurityConfig.java
=> feat: spring security 의존성 추가

src/main/java/curevengers/petit_cure/controller/testhome.java, src/main/resources/application.properties, src/main/resources/static/css/MyPage.css, src/main/resources/static/css/ResultSheet.css, src/main/resources/static/css/company.css, src/main/resources/templates/MyPage.html, src/main/resources/templates/ResultSheet.html, src/main/resources/templates/company.html, src/main/resources/templates/dpcheck.html, src/main/resources/templates/main.html
2024-11-27일 마이페이지 우울증결과지 회사소개 html,css로 해놨구용 회사소개는 연동해놨습니다 그러니 머지해주세요....ㅎ 부탁드려요><
=> feat:  마이페이지, 우울증결과지,회사소개

build.gradle, src/main/java/curevengers/petit_cure/Dao/MemberMapper.java, src/main/java/curevengers/petit_cure/Service/UserServiceImpl.java, src/main/java/curevengers/petit_cure/controller/EmailController.java, src/main/java/curevengers/petit_cure/controller/ProductController.java, src/main/java/curevengers/petit_cure/controller/memberController.java, src/main/java/curevengers/petit_cure/controller/testhome.java, src/main/java/curevengers/petit_cure/security/SecurityConfig.java, src/main/java/curevengers/petit_cure/security/UsernamePasswordAuthenticationFilter.java, src/main/java/curevengers/petit_cure/security/authenticationProvider.java, src/main/java/curevengers/petit_cure/security/handler/AuthenticationFailureHandlerImpl.java, src/main/java/curevengers/petit_cure/security/handler/AuthenticationSuccessHandlerImpl.java, src/main/java/curevengers/petit_cure/security/userdetailsService.java, src/main/resources/mappers/membermapper.xml, src/main/resources/templates/login.html, src/main/resources/templates/main.html, src/main/resources/templates/mplus.html
드디어,,,,구현하다,,
로그인하면 마이페이지 버튼 생깁니다.
=> feat:spring security 완성

src/main/java/curevengers/petit_cure/Dao/UserMapper.java, src/main/java/curevengers/petit_cure/Dto/commentDTO.java, src/main/java/curevengers/petit_cure/Dto/pageDTO.java, src/main/java/curevengers/petit_cure/Service/testService.java, src/main/java/curevengers/petit_cure/Service/testServiceImpl.java, src/main/java/curevengers/petit_cure/controller/testhome.java, src/main/resources/mappers/mapper.xml, src/main/resources/static/css/write.css, src/main/resources/templates/Q&A.html, src/main/resources/templates/qaview.html, src/main/resources/templates/qawrite.html
=> feat : 댓글 기능 구현

src/main/resources/static/css/company.css, src/main/resources/templates/company.html
=> feat:  회사소개 마이페이지 수정함

src/main/java/curevengers/petit_cure/controller/AuthController.java, src/main/java/curevengers/petit_cure/controller/ProductController.java, src/main/java/curevengers/petit_cure/security/JwtFilter.java, src/main/java/curevengers/petit_cure/security/SecurityConfig.java, src/main/resources/templates/login.html
=> feat:spring security로그인

src/main/java/curevengers/petit_cure/Dao/UserMapper.java, src/main/java/curevengers/petit_cure/Service/testService.java, src/main/java/curevengers/petit_cure/Service/testServiceImpl.java, src/main/java/curevengers/petit_cure/controller/testhome.java, src/main/resources/mappers/mapper.xml, src/main/resources/templates/freeBoard.html, src/main/resources/templates/qaview.html, src/main/resources/templates/view.html
=> feat : 게시판 신고기능

src/main/resources/templates/healthcheckresult.html
=> feat: API 구현중에 있습니다

src/main/java/curevengers/petit_cure/controller/testhome.java, src/main/resources/mappers/dpboardmapper.xml, src/main/resources/templates/dpview.html, src/main/resources/templates/freeBoard.html
=> fix : 우울증 게시판 댓글 수정

build.gradle, src/main/java/curevengers/petit_cure/Dao/UserMapper.java, src/main/java/curevengers/petit_cure/Dto/QABoardDTO.java, src/main/java/curevengers/petit_cure/Dto/dpBoardDTO.java, src/main/java/curevengers/petit_cure/Dto/dpboard_attachDTO.java, src/main/java/curevengers/petit_cure/Dto/pageDTO.java, src/main/java/curevengers/petit_cure/Dto/qaboard_attachDTO.java, src/main/java/curevengers/petit_cure/Service/dpBoardService.java, src/main/java/curevengers/petit_cure/Service/dpBoardServiceImpl.java, src/main/java/curevengers/petit_cure/Service/testService.java, src/main/java/curevengers/petit_cure/Service/testServiceImpl.java, src/main/java/curevengers/petit_cure/controller/testhome.java, src/main/resources/application-private.properties, src/main/resources/application.properties, src/main/resources/mappers/dpboardmapper.xml, src/main/resources/mappers/mapper.xml, src/main/resources/templates/freeBoard.html, src/main/resources/templates/qaview.html, src/main/resources/templates/qawrite.html, src/main/resources/templates/view.html
=> feat : 게시판 첨부파일 기능 구현

src/main/java/curevengers/petit_cure/Dao/UserMapper.java, src/main/java/curevengers/petit_cure/Service/dpBoardServiceImpl.java, src/main/java/curevengers/petit_cure/Service/testService.java, src/main/java/curevengers/petit_cure/Service/testServiceImpl.java, src/main/java/curevengers/petit_cure/controller/testhome.java, src/main/resources/mappers/mapper.xml, src/main/resources/static/css/freeBoard.css, src/main/resources/templates/Q&A.html, src/main/resources/templates/dpBoard.html, src/main/resources/templates/freeBoard.html, src/main/resources/templates/view.html
=> feat : 게시판 나열 구현

src/main/java/curevengers/petit_cure/Dao/UserMapper.java, src/main/java/curevengers/petit_cure/Dto/alertDTO.java, src/main/java/curevengers/petit_cure/Dto/boardLikeDTO.java, src/main/java/curevengers/petit_cure/Service/testService.java, src/main/java/curevengers/petit_cure/Service/testServiceImpl.java, src/main/java/curevengers/petit_cure/controller/memberController.java, src/main/java/curevengers/petit_cure/controller/testhome.java, src/main/java/curevengers/petit_cure/kakaoapi/kakaoController.java, src/main/java/curevengers/petit_cure/security/Provider/authenticationProvider.java, src/main/java/curevengers/petit_cure/security/SecurityConfig.java, src/main/java/curevengers/petit_cure/security/userdetailsService.java, src/main/resources/mappers/mapper.xml, src/main/resources/mappers/membermapper.xml, src/main/resources/templates/kakaomplus.html, src/main/resources/templates/qaview.html
=> feat:추천, 신고 추가 구현

src/main/java/curevengers/petit_cure/controller/memberController.java, src/main/resources/static/css/MyPage.css, src/main/resources/static/css/member.css, src/main/resources/static/css/memberupdate.css, src/main/resources/templates/MyPage.html, src/main/resources/templates/company.html, src/main/resources/templates/dpCheckResult.html, src/main/resources/templates/memberdelete.html, src/main/resources/templates/memberupdate.html
=> feat: 마이페이지 수정했어용

src/main/java/curevengers/petit_cure/Service/testServiceImpl.java, src/main/java/curevengers/petit_cure/controller/testhome.java, src/main/java/curevengers/petit_cure/security/SecurityConfig.java, src/main/resources/static/css/main.css, src/main/resources/templates/freeBoard.html, src/main/resources/templates/main.html, src/main/resources/templates/view.html
=> feat : 메인페이지 최고글 기능 추가(미완)

src/main/java/curevengers/petit_cure/Dao/UserMapper.java, src/main/java/curevengers/petit_cure/Dao/dpBoardMapper.java, src/main/java/curevengers/petit_cure/Dto/dpboardLikeDTO.java, src/main/java/curevengers/petit_cure/Dto/freeBoardDTO.java, src/main/java/curevengers/petit_cure/Dto/freeboardLikeDTO.java, src/main/java/curevengers/petit_cure/Dto/qaboardLikeDTO.java, src/main/java/curevengers/petit_cure/Service/dpBoardService.java, src/main/java/curevengers/petit_cure/Service/dpBoardServiceImpl.java, src/main/java/curevengers/petit_cure/Service/testService.java, src/main/java/curevengers/petit_cure/Service/testServiceImpl.java, src/main/java/curevengers/petit_cure/controller/memberController.java, src/main/java/curevengers/petit_cure/controller/testhome.java, src/main/resources/mappers/dpboardmapper.xml, src/main/resources/mappers/mapper.xml, src/main/resources/templates/dpBoard.html, src/main/resources/templates/dpview.html, src/main/resources/templates/mplus.html, src/main/resources/templates/qaview.html, src/main/resources/templates/view.html
=> feat : 자유게시판 및 우울증게시판에 추천 및 신고 버튼 기능 구현

src/main/java/curevengers/petit_cure/Service/allBoardService.java, src/main/resources/static/css/main.css
=> feat: 뭔지모르겠지만 많이 헀어용

src/main/java/curevengers/petit_cure/Service/allBoardService.java, src/main/resources/templates/mplus.html
=> feat : 회원가입화면에서 이메일 발송 시 시간초 설정

src/main/resources/static/css/main.css, src/main/resources/templates/main.html
=> feat : 메인화면 수정

src/main/java/curevengers/petit_cure/Dao/MemberMapper.java, src/main/java/curevengers/petit_cure/Dto/myActivityDTO.java, src/main/java/curevengers/petit_cure/Service/UserServiceImpl.java, src/main/java/curevengers/petit_cure/Service/userService.java, src/main/java/curevengers/petit_cure/controller/memberController.java, src/main/resources/mappers/membermapper.xml, src/main/resources/static/css/main.css, src/main/resources/templates/MyPage.html, src/main/resources/templates/main.html
=> feat : 메인페이지 게시판 탑3 출력 기능 추가

src/main/resources/static/css/main.css, src/main/resources/static/css/sticky.css, src/main/resources/templates/main.html
=> fix : 메인화면 깨진 것 복구

src/main/java/curevengers/petit_cure/controller/memberController.java, src/main/resources/static/css/main.css, src/main/resources/templates/MyPage.html, src/main/resources/templates/main.html
=> fix : 사이드바 zindex설정 수정

src/main/java/curevengers/petit_cure/controller/AdminController.java, src/main/resources/static/css/main.css, src/main/resources/templates/Q&A.html, src/main/resources/templates/access-denied.html, src/main/resources/templates/alertPage.html, src/main/resources/templates/alertview.html, src/main/resources/templates/button.html, src/main/resources/templates/company.html, src/main/resources/templates/dpBoard.html, src/main/resources/templates/freeBoard.html, src/main/resources/templates/login.html, src/main/resources/templates/loginerror.html, src/main/resources/templates/main.html, src/main/resources/templates/memberupdate.html, src/main/resources/templates/mplus.html, src/main/resources/templates/withdrawview.html
=> feat:사이드바 구현

src/main/java/curevengers/petit_cure/controller/memberController.java, src/main/resources/mappers/mapper.xml, src/main/resources/mappers/membermapper.xml, src/main/resources/templates/MyPage.html, src/main/resources/templates/Q&A.html, src/main/resources/templates/main.html
=> feat : 메인페이지 해당 글로 이동 기능 추가

src/main/java/curevengers/petit_cure/common/util/ExplanationMapper.java, src/main/java/curevengers/petit_cure/controller/HealthCheckController.java, src/main/java/curevengers/petit_cure/controller/PDFController.java, src/main/resources/templates/healthcheckresult.html
=> fix : PDF 화면 수정중

src/main/java/curevengers/petit_cure/controller/testhome.java, src/main/resources/templates/dpview.html, src/main/resources/templates/qaview.html
=> fix:Q&A에러수정
